version: '2.1'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8000:80
        depends_on:
            - app
        container_name: project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_app

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: syncwords_api
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
        ports:
            - 8101:5432
        container_name: project_db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

#    db:
#        image: postgres:14.1-alpine
#        restart: always
#        environment:
#            - POSTGRES_USER=postgres
#            - POSTGRES_PASSWORD=postgres
#        ports:
#            - 8101:3306
#        volumes:
#            - db:/var/lib/postgresql/data
#        container_name: project_db
#
#volumes:
#    db:
#        driver: local
